name: 'test-pipelines'
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  checkout:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  frontend:
    uses: jonasthim/reusable-workflows/.github/workflows/frontend-lambda-pipeline.yml@main
    secrets: inherit