name: 'test-pipelines'
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
env:
  npm.publish: true
jobs:
  frontend:
    uses: jonasthim/reusable-workflows/.github/workflows/frontend-lambda-pipeline.yml@main
    secrets: inherit
